### ISSUE TITLE
Can PEX bundle a Python interpreter too?

### ISSUE THREAD

**Issue by dclong** [pex-tool/pex#1007]
Is it possible for PEX to bundle a Python interpreter too so that the target machine does not even need a Python to be installed?

**Comment by jsirois** [comment]
It could, but this is no easy thing. See #636 for discussion of this in the context of Google's "par" which inspired Pex. In that case, Google controlled the OS and could bundle a known python interpreter for a known target Ubuntu linux variant. Pex needs to support ~any linux variant plus OSX across many versions.

If you can suggest some way Pex could do this and retain its current "runs anywhere" (Python 2.7 or 3.5+ Linux or Mac) profile though, I agree this would be a killer feature.

**Comment by dclong** [comment]
@jsirois Thank you for the explanation!

**Comment by jsirois** [comment]
I'm re-opening since #2096 is about to ship and I'll let the PR closing that issue close this as well for better cross-reference.

**Comment by jsirois** [comment]
With the release of Pex 2.11.0, you can now add `--scie {eager,lazy}` to your Pex command line and get a PEX with interpreter included.
