### ISSUE TITLE
Specifying `--platform`in `lock create` impedes referring to sdists

### ISSUE THREAD

**Issue by thejcannon** [pex-tool/pex#2005]
Both:
- `pex3 lock create --platform manylinux_2_31_x86_64-cp-38-cp38 timeout-decorator~=0.4`
- `pex3 lock create --style sources --platform manylinux_2_31_x86_64-cp-38-cp38 timeout-decorator~=0.4`

result in an error because `timeout-decorator` is an `sdist`-only package.

**Comment by jsirois** [comment]
This was fixed by #2075 and released in 2.1.125: https://github.com/pex-tool/pex/releases/tag/v2.1.125
