### ISSUE TITLE
unittest.main() doesn't work

### ISSUE THREAD

**Issue by guoshimin** [pex-tool/pex#210]
Background:
A typical python unit test code file looks like

```
import unittest

class MyTest(unittest.TestCase):
  def test_xyz(self):
    ...

if __name__ == '__main__':
  unittest.main()
```

`unittest.main` by default runs all the test cases in module `__main__`.

`pex` executes the entry point via `runpy.run_module(module_name, run_name='__main__')`: https://github.com/pantsbuild/pex/blob/a253efd4a4d9f33f5ac7f6f397902f62fb1e517f/pex/pex.py#L421

This sets `__name__` to be `__main__` in the entry point's execution context, and therefore the `if` check in the example code above passes. However, when `unittest.main()` tries to load the `__main__` module, what it loads is the `__main__.py` file generated by pex, not the entry point.

A simple fix is to specify `alter_sys=True` when invoking `runpy.run_module`, which will set `sys.modules[__name__]` to the entry point code.

**Comment by mikekap** [comment]
The same root cause (wrong `sys.modules` entry) prevents `pkg_resources.resource_*` from working in the entry point when using `__name__` as the argument.

**Comment by jsirois** [comment]
This was fixed some time ago and now works:
```
:; cat test.py
import unittest

class MyTest(unittest.TestCase):
  def test_xyz(self):
    assert False, "Proving test ran (and failed)."

if __name__ == '__main__':
  unittest.main()


:; pex -V
2.16.0
:; pex --exe test.py -otest.pex
:; ./test.pex
F
======================================================================
FAIL: test_xyz (__main__.MyTest.test_xyz)
----------------------------------------------------------------------
Traceback (most recent call last):
  File "/home/jsirois/.pex/unzipped_pexes/a029f272ccacc2894c95f032ab2e58b930897223/__pex_executable__.py", line 5, in test_xyz
    assert False, "Proving test ran (and failed)."
           ^^^^^
AssertionError: Proving test ran (and failed).

----------------------------------------------------------------------
Ran 1 test in 0.000s

FAILED (failures=1)
```
