### ISSUE TITLE
How to bootstrap external pex files within running Python interpreter

### ISSUE THREAD

**Issue by dineshkumar20** [pex-tool/pex#2405]
I'm currently using `pex_bootstrapper.bootstrap_pex_env()` to bootstrap imports from an external PEX file within a running Python interpreter. It's working for the current session, but not persistently across other sessions. The reason is I don't want to bootstrap the PEX file every time because it's taking a few seconds. Is there a way to permanently append the code from the PEX file to `sys.path`?

**Comment by jsirois** [comment]
There are 18 ways to do this, but using Pex APIs is not one. Pex supports nothing except its command line interface.

One is to build the PEX with `--include tools` and then run `PEX_TOOLS=1 /the/python/I/want/bin/python ./my.pex venv /right/here`. That will take several seconds, but just once.  Now run `/right/here/bin/python` as many times as you want to get as many REPL sessions as you want with standard venv overhead.

**Comment by dineshkumar20** [comment]
@jsirois Thanks you, Will this append the pex code to default python environment ?

**Comment by dineshkumar20** [comment]
If possible, could you please share the document link to read more about this?

**Comment by jsirois** [comment]
Ok, then another way is to re-build the PEX with `--venv prepend --venv-use-site-packages-copies` and then, inside the airflow session, issue:
```
import sys
sys.path.append(<path to PEX>)
import __pex__

# Now go about your session as normal
```

The `--venv ...` should help with the startup times but are not absolutely necessary. You should experiment.

**Comment by jsirois** [comment]
There are no high-level docs for any of this yet, you'd have to have read release notes or else studied `pex --help`.

**Comment by dineshkumar20** [comment]
@jsirois I have a question. If I use `sys.path.append` in a Python script, would it work in another Python session? 
This will not include 3rd party packages, right?

**Comment by dineshkumar20** [comment]
Sure, Thank you so much!

**Comment by jsirois** [comment]
@dineshkumar20 any luck?

**Comment by dineshkumar20** [comment]
@jsirois I've tried this method, but sometimes it is taking more time than `pex_bootstrapper.bootstrap_pex_env()`
Also this approach worked without these arguments as well `--venv prepend --venv-use-site-packages-copies`

```bash
➜  ~ pex openai-whisper -o openai-whisper.pex
➜  ~ python3
Python 3.9.6 (default, Oct 18 2023, 21:40:26)
[Clang 17.0.2 ] on darwin
Type "help", "copyright", "credits" or "license" for more information.
>>> import datetime
>>> import sys
>>> print(datetime.datetime.now())
2024-05-10 13:01:59.044270
>>> sys.path.append('openai-whisper.pex')
>>> import __pex__
>>> print(datetime.datetime.now())
2024-05-10 13:02:00.323626
>>> import torch
>>> print(datetime.datetime.now())
2024-05-10 13:02:08.597646
>>>```

**Comment by dineshkumar20** [comment]
I've noticed that this approach doesn't seem to be working for pex files generated by the pantsbuild system. Any thoughts on why that might be?

BUILD
```
pex_binary(
    name="whisper_speech_recognition_app",
    entry_point="whisper_speech_recognition/interface/main.py",
    dependencies=[
        ":pkg",
    ],
    layout="packed",
    execution_mode="venv",
    venv_site_packages_copies=True,
)
```

**Comment by benjyw** [comment]
Hey @dineshkumar20 , as you've noticed, Pants Slack or Pants GH issues are the right forums for questions about Pants. Pex has many configuration options, and Pants naturally uses various subsets of them in various ways. The PEX project itself can't really know about, or account for, those.

**Comment by benjyw** [comment]
Hopefully the response you got on Pants Slack is helpful, if not that is the right place to continue the conversation.

**Comment by jsirois** [comment]
I can't comment on Pants. I can better comment on your use case though if you give me very concrete details so that I could reproduce your PEX contents (or at least all the 3rdparty dependencies) and your Airflow environment.

**Comment by jsirois** [comment]
> @jsirois I've tried this method, but sometimes it is taking more time than `pex_bootstrapper.bootstrap_pex_env()`
> Also this approach worked without these arguments as well `--venv prepend --venv-use-site-packages-copies`
> 
> ```bash
> ➜  ~ pex openai-whisper -o openai-whisper.pex
> ➜  ~ python3
> Python 3.9.6 (default, Oct 18 2023, 21:40:26)
> [Clang 17.0.2 ] on darwin
> Type "help", "copyright", "credits" or "license" for more information.
> >>> import datetime
> >>> import sys
> >>> print(datetime.datetime.now())
> 2024-05-10 13:01:59.044270
> >>> sys.path.append('openai-whisper.pex')
> >>> import __pex__
> >>> print(datetime.datetime.now())
> 2024-05-10 13:02:00.323626
> >>> import torch
> >>> print(datetime.datetime.now())
> 2024-05-10 13:02:08.597646
> >>>```

Is this the same timing you get the 2nd-Nth time you start a repl though? It shouldn't be. Only the 1st PEX activation should be slow.

**Comment by dineshkumar20** [comment]
> > @jsirois I've tried this method, but sometimes it is taking more time than `pex_bootstrapper.bootstrap_pex_env()`
> > Also this approach worked without these arguments as well `--venv prepend --venv-use-site-packages-copies`
> > ```shell
> > ➜  ~ pex openai-whisper -o openai-whisper.pex
> > ➜  ~ python3
> > Python 3.9.6 (default, Oct 18 2023, 21:40:26)
> > [Clang 17.0.2 ] on darwin
> > Type "help", "copyright", "credits" or "license" for more information.
> > >>> import datetime
> > >>> import sys
> > >>> print(datetime.datetime.now())
> > 2024-05-10 13:01:59.044270
> > >>> sys.path.append('openai-whisper.pex')
> > >>> import __pex__
> > >>> print(datetime.datetime.now())
> > 2024-05-10 13:02:00.323626
> > >>> import torch
> > >>> print(datetime.datetime.now())
> > 2024-05-10 13:02:08.597646
> > >>>```
> > ```
> 
> Is this the same timing you get the 2nd-Nth time you start a repl though? It shouldn't be. Only the 1st PEX activation should be slow.

Yes, you're correct. Only the first time it's taking so much time.

**Comment by jsirois** [comment]
> Yes, you're correct. Only the first time it's taking so much time.

Great. That's what I expected. I can't offer you better than that unfortunately.

**Comment by dineshkumar20** [comment]
Thank you so much!

**Comment by jsirois** [comment]
And that should be ~exactly the same timing as using the `pex_bootstrapper` private API - under the covers that's roughly all `import __pex__` does.

**Comment by jsirois** [comment]
@dineshkumar20 I'm going to close this as an answered question unless you have more details you want to hash through.

**Comment by dineshkumar20** [comment]
Oh, okay. Thanks for sharing the details. You mentioned there are 18 ways to do this. If you happen to have any documents or notes on this, could you please share them here? It would really help me out in the future if I encounter any issues.

**Comment by dineshkumar20** [comment]
> @dineshkumar20 I'm going to close this as an answered question unless you have more details you want to hash through.

Sure 👍

**Comment by jsirois** [comment]
As I said above, there are no docs except those linked in the repo (https://docs.pex-tool.org/) and via `pex --help`, `pex3 --help` and `pex-tools --help` (these are the 3 console scripts you get when you `pip install pex`).
