### ISSUE TITLE
Can't pass 'cwd' to pex.run()

### ISSUE THREAD

**Issue by ericzundel** [pex-tool/pex#25]
cwd is an option for subprocess.Popen, but the way pants.run() is written, you can't override it.

I don't really need this feature, I just ran into it when trying to call it from pants with cwd=None.

**Comment by jsirois** [comment]
Although it's still true the `PEX.run()` API (I think by `pants.run()` you meant PEX.run()`) does not allow specifying cwd in practice, it's also true that in the bump from Pex 1.x to 2.x support for all code APIs was dropped and Pex only supports its CLI as the SEMVER'd interface. As such, I'll close this as answered and obsolete.
