### ISSUE TITLE
Spark docs

### ISSUE THREAD

**Issue by stefanondisponibile** [pex-tool/pex#2560]
https://spark.apache.org/docs/latest/api/python/user_guide/python_packaging.html#using-pex
> However, .pex file does not include a Python interpreter itself under the hood so all nodes in a cluster should have the same Python interpreter installed.

Is this still true?

https://docs.pex-tool.org/scie.html
> You can include a Python interpreter in your PEX by adding --scie eager to your pex command line. Instead of a traditional [PEP-441](https://peps.python.org/pep-0441/) PEX zip file, you’ll get a native executable that contains both a Python interpreter and your PEX’d code.

**Comment by jsirois** [comment]
As you have discovered, no. And that makes sense, presumably an external project like Spark will always lag on news.

**Comment by jsirois** [comment]
I'm going to close this as an answered question, but please speak up if there is more.

**Comment by stefanondisponibile** [comment]
Thank you @jsirois, that's awesome!
