### ISSUE TITLE
return in finally swallows exceptions

### ISSUE THREAD

**Issue by iritkatriel** [pex-tool/pex#2573]
In https://github.com/pex-tool/pex/blob/386af2e270855c71acc5c3226ef90d89960c10ba/pex/common.py#L394C8-L394C17. there is a `return` statement in a `finally` block, which would swallow any in-flight exception.

This means that an exception other than `OSError` (including a `BaseException` such as `KeyboardInterrupt`) is raised from the `try` body, or any exception is raised from the `except:` clause, it will not propagate on as expected.

See also https://docs.python.org/3/tutorial/errors.html#defining-clean-up-actions.

**Comment by jsirois** [comment]
Thanks, that indeed looks whacky! It probably took more effort to write your OP issue out here than submit a fix. Do you want to take a crack at it?

**Comment by jsirois** [comment]
I may just knock this out to get in the 2.20.4 bug fix release train going out this afternoon. I'll assign the issue to myself and label in-progress if so, so that I don't step on your toes.

**Comment by benjyw** [comment]
Hi @iritkatriel , thanks for the bug report. Out of curiosity, how did you come to notice this?

**Comment by iritkatriel** [comment]
> Hi @iritkatriel , thanks for the bug report. Out of curiosity, how did you come to notice this?

I'm doing some analysis on how people use/abuse finally, so running static analysis on lots of open source code. I report issues as I see them.
