### ISSUE TITLE
macOS pex SCIE is not code signed, so macOS tries to convince me to not run it

### ISSUE THREAD

**Issue by tdyas** [pex-tool/pex#2621]
The macOS SCIE for Pex (for example, [this one](https://github.com/pex-tool/pex/releases/download/v2.25.2/pex-macos-x86_64)) is not digitally signed via Apple's `codesign` (or other applicable tool).

This is an issue because macOS 15.1.x really goes to great lengths to _dissuade_ users from running such binaries. This will be a negative UX issue for Pants if Pants downloads a SCIE of Pex to use it. Users likely will not know why macOS is showing these modals in that case, which could erode user trust and moreover prevent Pants from using the Pex SCIE since the user may not go through three modals and/or even find the approval button in the security settings.

What macOS does:

1. First, it shows a modal where the only two choices are to close the modal or move the file to the trash. Notably, no mention is made in the modal of how to approve the binary in the Security pane of the System Settings.

<img width="266" alt="Screenshot 2024-12-11 at 17 05 35" src="https://github.com/user-attachments/assets/2eeefc72-7095-4466-ba21-eab100be9d00" />

2. Next, even after approving the binary, macOS shows a second modal:

<img width="276" alt="Screenshot 2024-12-11 at 17 07 13" src="https://github.com/user-attachments/assets/b2368b95-9e70-4cec-9679-cf9f5d053cce" />

3. And even when selecting "Open anyway", macOS shows a third modal to ask for the admin password:

<img width="265" alt="Screenshot 2024-12-11 at 17 07 21" src="https://github.com/user-attachments/assets/e3beb94e-61c7-40a9-bf26-093014f23064" />

**Comment by tdyas** [comment]
What is blocking us from code signing beyond paying the money to Apple for their developer program (and then doing the work to sign the binary with `codesign`)?

**Comment by jsirois** [comment]
How is Pants not hitting this already with scie-pants. Is macOs taking the unofficial keg / tap brew thing as some sort of shield? This is really laughable, because that sort of has to be it.

**Comment by tdyas** [comment]
Your observation is spot on. The brew recipe just blindly approves the binary (and just the fact that it even has the ability to do so is suspect ...): https://github.com/pantsbuild/homebrew-tap/blob/46d0ecbaebabdf52ae300e9f4719efe6e63ac8ab/Casks/pants.rb#L44-L46

**Comment by jsirois** [comment]
All that said, I'd probably try using https://gregoryszorc.com/docs/pyoxidizer/main/tugger.html if I must. I'll be damned if I bow to Apple and be forced into using their tools on an illegal to virtualize OS.

**Comment by tdyas** [comment]
Still requires paying the Apple tax for the developer program to obtain a code signing certificate even for a tool like Tugger. The particular code signing tool is beside the point.

**Comment by jsirois** [comment]
Understood.

But also, are you partially inventing a problem here? For example, the science (a-scie/lift) tests download and run scie-jump binaries. The Mac shards pass with no signing and no brew middleman. It seems Apple allows non-interactive use of untrusted binaries?! Even more laughable security theatre it seems, but I am not a security expert.

**Comment by tdyas** [comment]
https://github.com/Homebrew/brew/blob/master/Library/Homebrew/cask/quarantine.rb is a fun read. The quarantine mechanism is keyed on the presence of an xattr, so removing the xattr essentially blesses the file.

**Comment by jsirois** [comment]
Ok, but maybe simpler, can you just write a bash script that curls the Pex PEX scie and then tries to run it - say just printing its version? If you can run that script that seems to vet the approach or rule it out if pop-ups ensue.

**Comment by tdyas** [comment]
No need. It took me all of 30 minutes to get Pex SCIE working: https://github.com/pantsbuild/pants/pull/21755

I'll need to see full CI fun pass, but `./pants fmt lint check` works fine locally for me.

So we can close this. My concerns from trying to run the Pex SCIE manually evaporated after no pop-ups appeared in running it from within Pants.

**Comment by jsirois** [comment]
Ok, excellent. Be careful out there - mac is pretty shady!
