### ISSUE TITLE
increase test coverage in a few key areas

### ISSUE THREAD

**Issue by kwlzn** [pex-tool/pex#273]
we've been having a bumpy time with release quality lately - several regressions have made their way out via inbound PRs due to inadequate test coverage. I think we should invest some time in improving test coverage in a few key areas:
- the pex repl (I recently introduced a change that apparently broke the repl and no tests caught it)
- various real world package resolve scenarios (#263 -> `backoff`, #231 -> `pygments-markdown-lexer`, etc)
- interpreter and abi handling

others?

**Comment by jsirois** [comment]
The Pex repl is now both more fully customized and fairly rigorously tested using pexpect. The IT coverage of real world packages is now quite extensive over a broad swath of time. Although test coverage can always get better, I think these concerns have been addressed in the interim. Release cadence is both at a good clip and releases are quite stable.
