### ISSUE TITLE
Cached package source has priority over wheel, preventing build?

### ISSUE THREAD

**Issue by ariscn** [pex-tool/pex#276]
I have an app which depends on, say, the cryptography package. I'm building on OS X for deployment on Linux, so I use `-platform linux_x86_64 -f ~/.pip-wheelhouse`.

Oops, I don't have a wheel for cryptography, let's jump on a Linux box, run `pip wheel cryptography` and copy the artifact from there to my local `~/.pip-wheelhouse`.

At this point, I expect pex to build my application successful. However, it continues to fail with:

```
pex.resolver.Untranslateable: Could not get distribution for SourcePackage('file:///Users/pikeas/.pex/build/cryptography-1.4.tar.gz') on platform linux_x86_64
```

The only way I've found to fix it is to `rm -rf ~/.pex/build/<package>.tar.gz`.

This has happened across several packages, including just now with MarkupSafe (no wheel on PyPi, built one on a Linux machine per above). It looks like the source package (.tar.gz) in the wheelhouse directory always takes priority over a wheel (.whl). Removing the source file allows pex to find the wheel.

**Comment by kwlzn** [comment]
I believe this just comes down to the way the resolver cache in pex works. essentially, once something is resolved the end product of the resolve will be cached for the duration of the resolver cache ttl. the default ttl is `None`, which causes pex to essentially reuse the cache dir forever. it should not be the case that pex prefers sdists over bdists tho.

I think a simple workaround here would be to pass one of either of these flags:

```
    --disable-cache     Disable caching in the pex tool entirely.
    --cache-ttl=CACHE_TTL
                        The cache TTL to use for inexact requirement
                        specifications.
```

however it's certainly a problem area that I'd like to address soon.

any chance you have reliable repro steps for any of the cases you're experiencing? it'd be good to capture that here.

**Comment by jsirois** [comment]
The bespoke Pex resolver that had this issue has since been replaced by Pip and no longer exhibits this problem.
