### ISSUE TITLE
importing pex.variables will may look at disk and update state

### ISSUE THREAD

**Issue by digwanderlust** [pex-tool/pex#289]
https://github.com/pantsbuild/pex/blob/master/pex/variables.py#L36

When a module imports variables it creates an ENV object which checks the env variables and stores them.  It also may read files from disk.  In most cases this is probably an unexpected side effect.  Since many modules inside pex import variables the user is often more removed from this effect since they may not be directly importing variables.

Proposed solution is to change Variables to load values lazily on first access.  This will be a change in behavior and may impact users who implicitly rely on this behavior when using pex as a library.

**Comment by sixninetynine** [comment]
do you mean having a deferred `__init__` triggered off a `__getattr__` call?

I'm just an innocent bystander, but I'm curious what behavior you want to see. I assume you are aiming to avoid code execution upon import (a clear anti-pattern, to be sure). Yeah?

**Comment by jsirois** [comment]
I'm going to close this as obsolete since Pex discontinued support for any API in the switch to 2.x. Its only interface since then has been the CLI, with strict backwards compatibility guarantees.
