### ISSUE TITLE
PexBuilder.add_dist_location ignores name argument

### ISSUE THREAD

**Issue by benley** [pex-tool/pex#294]
https://github.com/pantsbuild/pex/blob/2fc3f73dcc8263edc965bb95e593787037207b64/pex/pex_builder.py#L288

It looks like `add_dist_location` is supposed to pass the `name` argument along to `DistributionHelper.distribution_from_path`, but it currently does nothing with it.

**Comment by jsirois** [comment]
This was cleaned up in #1784. The name arguments are now gone in all code paths.
