### ISSUE TITLE
Getting "File exists" error upon concurrent start of pex package

### ISSUE THREAD

**Issue by sitaktif** [pex-tool/pex#401]
pex version: 1.2.9

In `pex/environment.py: force_local()`, the `os.rename(explode_tmp, explode_dir)` operation may fail because another process ran the pex (for the "first time") at the same time.

Looking at the `.pex/code` directory, we can see that indeed, the target directory (4042b3b39dfbb555b729eeb9f664f280069e1277) was created just before
```
$ ls ~/.pex/code | grep 515
drwxr-xr-x  3 usr grp  107 Aug 19 21:36 4042b3b39dfbb555b729eeb9f664f280069e1277
drwxr-xr-x  3 usr grp  107 Aug 19 21:36 4042b3b39dfbb555b729eeb9f664f280069e1277.de58f52453e24270b06046ec8695458f
$ stat 4042b3b39dfbb555b729eeb9f664f280069e1277 | grep Modify
Modify: 2017-08-19 21:36:59.976220274 -0700
$ stat 4042b3b39dfbb555b729eeb9f664f280069e1277.de58f52453e24270b06046ec8695458f | grep Modify
Modify: 2017-08-19 21:36:59.980220272 -0700
```

Suggestion: catch the case where the directory exists and pass, assuming that another instance of the pex did the job already.

**Comment by jsirois** [comment]
This style of inter-process concurrency bug has been fixed wholesale for a while now by moving to the `atomic_directory` abstraction throughout the code base:
https://github.com/pex-tool/pex/blob/27044bd7fb425725a705c3e7e776ed34e1c58b20/pex/atomic_directory.py#L236-L256

The implementation was hammered into its current shape by alot of very concurrent usage via the Pants v2 engine.
