### ISSUE TITLE
Possible incorrect entry in sys.path when using CPython 3.5.4

### ISSUE THREAD

**Issue by ncoghlan** [pex-tool/pex#440]
CPython 3.5.4 has a regression where the current directory may end up on sys.path when not using isolated mode and executing a zipfile or directory: https://bugs.python.org/issue32551

While I *haven't* confirmed definitively that the bug affects pex files, I also haven't been able to find anything in the pex code that asks the underlying interpreter to run in isolated mode, so my current assumption is that you'll be affected by the problem.

**Comment by kwlzn** [comment]
thanks for the heads up!

**Comment by ncoghlan** [comment]
I just realised my original comment wasn't completely clear on my suggested long term fix: I believe pex *should* be using isolated mode wherever possible, since picking up random per-user settings from the environment probably isn't something you really want. You'll just need to watch out for https://bugs.python.org/issue29319 (where `-I` and zipfile execution don't play nice in versions *before* 3.5.4)

Fortunately Eryk Sun figured out we'd slightly misdiagnosed the misbehaviour, so it doesn't actually introduce any new opportunities for running arbitrary code from user-controlled directories.

**Comment by jsirois** [comment]
Pex can't generally use `-I` since it never drops support for Pythons it adds support for; i.e we support Python 2.7. As such, we use `-sE` as our isolation mode consistently.  Not the same, but we do extra scrubbing on top of this depending on the execution mode (hermetic zipapp - more scrub, hermetic venv - just `-sE`).

I just checked and all looks well with modern Pex at least:
```console
:; pex -V
2.16.1

:; cat exe.py
import sys


if __name__ == "__main__":
    print(sys.argv)


# Traditional zipapp:
:; pex --exe exe.py -o test.pex
# Unpacks into a venv under PEX_ROOT at runtime and executes from that:
:; pex --exe exe.py --venv -o test-venv.pex
# A directory layout:
:; pex --exe exe.py --layout loose -o test-loose.pex

# Python 2.7:
:; python2.7 test.pex
['/home/jsirois/.pex/unzipped_pexes/f4050926525b5b4a4a79cfb0074ff0bd87050549/__pex_executable__.py']

:; python2.7 test-venv.pex
['/home/jsirois/.pex/venvs/659d6772697547758dcec95ec915ee1a1ba9e766/4be00ea3d6ac0f8202924551a48b88e54638da6e/lib/python2.7/site-packages/__pex_executable__.py']

:; python2.7 test-loose.pex/
['/home/jsirois/dev/pex-tool/pex/test-loose.pex/__pex_executable__.py']

# Python 3.5.4:
:; ~/.pyenv/versions/3.5.4/bin/python test.pex
['/home/jsirois/.pex/unzipped_pexes/f4050926525b5b4a4a79cfb0074ff0bd87050549/__pex_executable__.py']

:; ~/.pyenv/versions/3.5.4/bin/python test-venv.pex
['/home/jsirois/.pex/venvs/659d6772697547758dcec95ec915ee1a1ba9e766/436778cf09b8bdb4a5155f3b51ad4904c3b953da/lib/python3.5/site-packages/__pex_executable__.py']

:; ~/.pyenv/versions/3.5.4/bin/python test-loose.pex/
['/home/jsirois/dev/pex-tool/pex/test-loose.pex/__pex_executable__.py']

# Python 3.5.10:
:; ~/.pyenv/versions/3.5.10/bin/python test.pex
['/home/jsirois/.pex/unzipped_pexes/f4050926525b5b4a4a79cfb0074ff0bd87050549/__pex_executable__.py']

:; ~/.pyenv/versions/3.5.10/bin/python test-venv.pex
['/home/jsirois/.pex/venvs/659d6772697547758dcec95ec915ee1a1ba9e766/7aff4d0838cb9a4a402485f1f883a8fc85cc2bcd/lib/python3.5/site-packages/__pex_executable__.py']

:; ~/.pyenv/versions/3.5.10/bin/python test-loose.pex/
['/home/jsirois/dev/pex-tool/pex/test-loose.pex/__pex_executable__.py']
```

It took too long to see this and test things out, but I appreciate the warning @ncoghlan.
