### ISSUE TITLE
--allow-external/--allow-all-external doesn't work

### ISSUE THREAD

**Issue by wickman** [pex-tool/pex#64]
Looks like pypi changed the way it tags external packages.  Now you can have a direct download link from pypi.python.org/simple, just that it's tagged with an 'ext-download' tag.  We need to filter ext-download packages if follow_links is False.

**Comment by jsirois** [comment]
[PEP-470](https://peps.python.org/pep-0470/) removed support for externals altogether; so this support isn't needed any longer.
