### ISSUE TITLE
'AssertionError: Failed to cache distribution' is difficult to diagnose

### ISSUE THREAD

**Issue by baroquebobcat** [pex-tool/pex#644]
From reading the code around the assertion, I think there's a number of ways that the cache distribution might be missing something. I think it'd be nice if the errors here were more specific because there are a number of ways to try and resolve this. 

For example, deleting the cache directory might clear up some classes of error related to this. It's not clear from the current message that that's the case or even where the directory to investigate is located.

https://github.com/pantsbuild/pex/blob/8fd5e1b989224046cd0fb038cfebc11b4c10a8c9/pex/util.py#L188

**Comment by stuhood** [comment]
Saw another instance of this one.

Would a next step here be to give `DistributionHelper.distribution_from_path(target_dir)` a form that will fail with a useful exception? Or to add retry there?

**Comment by jsirois** [comment]
Yes. Although, a quick scan of usages seems to suggest it shouldn't be a new form, all callers should have to deal with the exception.

**Comment by jsirois** [comment]
With the switch from the the Pex bespoke resolver to Pip in 2.x and conversion of all disk cache reads and writes to using `atomic_directory`, this problem is both obsolete and no longer present in any similar form.
