### ISSUE TITLE
Making modules available at PEX build time

### ISSUE THREAD

**Issue by ghost** [pex-tool/pex#683]
I have a module, call it mysetuptools, which is a wrapper around the regular setuptools. All it does it wrap the setup() function and inject some additional useful classifier metadata that I need.

So a simple setup.py file might look something like:
```
    from mysetuptools import setup
    setup(name='foo', version='0.1')
```

In previous versions of the pex tool (as late as version 1.5.1, anyway), I could build a PEX based on this setup.py file by creating a virtual environment and installing both pex and mysetuptools into it. But when I try this now, I get a ModuleNotFoundError for mysetuptools from the run() method of SetuptoolsInstallerBase. It looks like it is no longer "seeing" the additional library I've installed in the virtual environment.

How can I make modules like mysetuptools available at PEX build time?

Possibly related: #236, #660

**Comment by jsirois** [comment]
I think #660 is the right answer here. Now that PEX vendors setuptools and wheel, prior venv leaks are eliminated.

**Comment by EricPetersonIBKR** [comment]
Ok understood. Is the implementation of #660 targeted for any particular future release yet?

**Comment by jsirois** [comment]
It isn't. Most / all work is currently coming from the pants community focused on supporting python 3 more fully and split runtimes (py2/py3 pexes). We do appreciate contributions of course, and can provide help.

**Comment by jsirois** [comment]
PEP-518 is indeed the way to support this and Pex 2.x supports PEP-517 / PEP-518 fully.
