### ISSUE TITLE
Support a restricted from of --inherit-path with a dist whitelist.

### ISSUE THREAD

**Issue by jsirois** [pex-tool/pex#764]
The idea would be able to say something like:
```
pex --inherit-path=prefer:setuptools --inherit-path=fallback:requests
```

IOW: the `--inherit-path` option becomes a list and it allows for whitelisting individual distributions, if named after a `:` (straw-man option syntax).

Broken out from #138 which is technically fixed, but from which spawned the whitelist idea for `--inherit-path`.

**Comment by benjyw** [comment]
Note that we have use-cases where it would be good to be able to whitelist just the PYTHONPATH, which is just a mild syntax extension of whitelisting a dist.

**Comment by benjyw** [comment]
Actually, that PYTHONPATH use-case is now handled by https://github.com/pantsbuild/pex/pull/989. 

The inherit_path mechanism should be about if and how to filter the
existing sys.path, when we might not know what's on it. We can use
the much simpler mechanism if we simply want to add some known
dirs to the sys.path.

**Comment by jsirois** [comment]
Yeah, I think bases are covered well enough now. Whitelisting would require creating a a temp dir and symlinking the necessary individual sys.path entry elements. For 1 distribution this is a symlink for each top-level module or package plus one more for the .dist-info dir. It's already known that symlinks like this don't always play well certain libraries (c.f.: `--venv-site-packages-copies`), so in the absence of any driving need I'll close this as not planned.
