### ISSUE TITLE
Support of intel packages

### ISSUE THREAD

**Issue by jdlesage** [pex-tool/pex#768]
I would like to package in a pex, the intel packages of the classic python numerical packages (numpy, scipy, etc.)
Pex seems not able to find the package that provides numpy because the name differs.
Here a simple reproducer:

_System description_
pex version: 1.6.11
python version: 3.6.3
OS: centos7

**Using classic numpy, it works**

`pex numpy -o numpy.pex`
`./numpy.pex -c "import numpy; print(numpy.__file__)"`

/home/jd.lesage/.pex/install/numpy-1.17.2-cp36-cp36m-manylinux1_x86_64.whl.0833169d405facf4fccb13d37dcbf723d0827c1e/numpy-1.17.2-cp36-cp36m-manylinux1_x86_64.whl/numpy/__init__.py

**Using intel numpy, import fails**
`pex intel_numpy -o intel_numpy.pex`
`./intel_numpy.pex -c "import numpy; print(numpy.__file__)"`

Traceback (most recent call last):
  File ".bootstrap/pex/pex.py", line 397, in execute
  File ".bootstrap/pex/pex.py", line 329, in _wrap_coverage
  File ".bootstrap/pex/pex.py", line 360, in _wrap_profiling
  File ".bootstrap/pex/pex.py", line 445, in _execute
  File ".bootstrap/pex/pex.py", line 484, in execute_interpreter
  File ".bootstrap/pex/pex.py", line 535, in execute_content
  File ".bootstrap/pex/compatibility.py", line 81, in exec_function
  File "-c <cmd>", line 1, in <module>
ModuleNotFoundError: No module named 'numpy'

**Comment by jsirois** [comment]
Alrighty - intel-numpy is an exceedingly odd package:
```
$ unzip -l intel_numpy-1.21.5-cp39-cp39-manylinux2014_x86_64.whl | grep numpy/__init__.py
    16819  2023-11-30 14:03   intel_numpy-1.21.5.data/data/lib/python3.9/site-packages/numpy/__init__.py
   133925  2023-11-30 14:03   intel_numpy-1.21.5.data/data/lib/python3.9/site-packages/numpy/__init__.pyi
```

It stuffs the code in data directories instead of at the top-level. This will never work with a traditional PEX, but things do work in `--venv` mode though:
```
$ pex intel-numpy --venv -o intel_numpy.pex && ./intel_numpy.pex -c "import numpy; print(numpy.__file__)"
/home/jsirois/.pex/venvs/440b59b00eab62a3ec204417f71948250dfe5db1/108a3ddc84230ab282ea6312e06cb68f51008ce5/lib/python3.9/site-packages/numpy/__init__.py:164: UserWarning: mkl-service package failed to import, therefore Intel(R) MKL initialization ensuring its correct out-of-the box operation under condition when Gnu OpenMP had already been loaded by Python process is not assured. Please install mkl-service package, see http://github.com/IntelPython/mkl-service
  from . import _distributor_init
/home/jsirois/.pex/venvs/440b59b00eab62a3ec204417f71948250dfe5db1/108a3ddc84230ab282ea6312e06cb68f51008ce5/lib/python3.9/site-packages/mkl_fft/_numpy_fft.py:206: SyntaxWarning: "is" with a literal. Did you mean "=="?
  elif norm is "forward":
/home/jsirois/.pex/venvs/440b59b00eab62a3ec204417f71948250dfe5db1/108a3ddc84230ab282ea6312e06cb68f51008ce5/lib/python3.9/site-packages/numpy/__init__.py
```

In general, building a pex with `--venv prepend --venv-site-packages-copies` will net you a runtime environment most compatible with what even atypical distributions expect. The cost is a slightly slower cold boot, but then faster runs from then forward. You can use `PEX_TOOLS=1 intel_numpy.pex venv --compile --site-packages-copies right/here` to explicitly turn the PEX file into a venv as well if, for example, you're building a Docker image from it.

**Comment by jsirois** [comment]
@jdlesage I'm going to close this as an answered question. The Pex `--venv` functionality did not exist in 2019, but it has now for several years and is generally what you want. You may also want to investigate `--sh-boot`.
