### ISSUE TITLE
Kill PEX_IGNORE_ERRORS

### ISSUE THREAD

**Issue by benjyw** [pex-tool/pex#774]
It's not a good idea to allow creation of a pex that we know has missing requirements.

**Comment by jsirois** [comment]
The introduction of `--exclude` in #2281, improved in #2409 and 1st released in [v2.1.151](https://github.com/pex-tool/pex/releases/tag/v2.1.151) actually necessitates this; so I'm going to close as not planned. #2426 tracks a safer version of `--exclude` that won't require ignoring errors, but cases still exist where `--exclude` is correct without replacement as outlined in #2097.
