### ISSUE TITLE
docs example error

### ISSUE THREAD

**Issue by assafgi** [pex-tool/pex#784]
Hi am using pex latest version on python 3.7.
I tried running your example ` pex sphinx sphinx_rtd_theme -c sphinx -o sphinx.pex`.
The result I get is: `pex.pex_builder.InvalidExecutableSpecification: Could not find script 'sphinx' in any distribution...`

**Comment by jsirois** [comment]
Thanks for pointing this out @assafgi. I finally got around to see this and the example, as well as others, are now updated and fixed. A preview of the fixed docs are here: https://jsirois.github.io/pex/buildingpex.html.  The next Pex release, which should happen before the end of this week, will contain those updates at https://docs.pex-tool.org/buildingpex.html.
