### ISSUE TITLE
PEX.clean_environment is used inconsistently

### ISSUE THREAD

**Issue by wickman** [pex-tool/pex#90]
If PEX_INTERPRETER is specified, it must be deleted prior to invoking subprocesses lest those subprocesses also drop into an interpreter.  Same goes for PEX_PYTHON, PEX_SCRIPT, etc.  However, deleting these environment variables is done haphazardly and should be done prior to invoking PEX.execute.  There are likely bugs hiding under the covers because of this.

**Comment by jsirois** [comment]
This is now done consistently just before any of the various execution modes here:
https://github.com/pex-tool/pex/blob/27044bd7fb425725a705c3e7e776ed34e1c58b20/pex/pex.py#L583-L587
https://github.com/pex-tool/pex/blob/27044bd7fb425725a705c3e7e776ed34e1c58b20/pex/pex.py#L148-L154
